// <auto-generated />
using System;
using Drandulette.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Drandulette.Migrations
{
    [DbContext(typeof(DranduletteContext))]
    partial class DranduletteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Drandulette.Controllers.Data.Models.Announcement", b =>
                {
                    b.Property<string>("announcementID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("body")
                        .HasColumnType("longtext");

                    b.Property<string>("brand")
                        .HasColumnType("longtext");

                    b.Property<string>("fuelType")
                        .HasColumnType("longtext");

                    b.Property<int>("hp")
                        .HasColumnType("int");

                    b.Property<string>("mailLogin")
                        .HasColumnType("longtext");

                    b.Property<int>("mileage")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .HasColumnType("longtext");

                    b.Property<string>("picsPath")
                        .HasColumnType("longtext");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("sellersComment")
                        .HasColumnType("longtext");

                    b.Property<string>("transmission")
                        .HasColumnType("longtext");

                    b.Property<double>("volume")
                        .HasColumnType("double");

                    b.Property<string>("wheelDrive")
                        .HasColumnType("longtext");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("announcementID");

                    b.ToTable("Announcement");
                });

            modelBuilder.Entity("Drandulette.Controllers.Data.Models.Announcement_comment", b =>
                {
                    b.Property<string>("announcment_commentID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("announcmentID")
                        .HasColumnType("longtext");

                    b.Property<string>("mailLogin")
                        .HasColumnType("longtext");

                    b.Property<string>("message")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("time")
                        .HasColumnType("datetime(6)");

                    b.HasKey("announcment_commentID");

                    b.ToTable("Announcement_comment");
                });

            modelBuilder.Entity("Drandulette.Controllers.Data.Models.Topic", b =>
                {
                    b.Property<string>("topicID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("mailLogin")
                        .HasColumnType("longtext");

                    b.Property<string>("time")
                        .HasColumnType("longtext");

                    b.Property<string>("topic_text")
                        .HasColumnType("longtext");

                    b.Property<string>("topic_theme")
                        .HasColumnType("longtext");

                    b.HasKey("topicID");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("Drandulette.Controllers.Data.Models.Topic_comment", b =>
                {
                    b.Property<string>("topic_commentID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("mailLogin")
                        .HasColumnType("longtext");

                    b.Property<string>("message")
                        .HasColumnType("longtext");

                    b.Property<string>("time")
                        .HasColumnType("longtext");

                    b.Property<string>("topicID")
                        .HasColumnType("longtext");

                    b.HasKey("topic_commentID");

                    b.ToTable("Topic_comment");
                });

            modelBuilder.Entity("Drandulette.Controllers.Data.Models.User", b =>
                {
                    b.Property<string>("mailLogin")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("moderator")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.HasKey("mailLogin");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
